//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProfessional.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,000,000")]
        public string DefaultMoney {
            get {
                return ((string)(this["DefaultMoney"]));
            }
            set {
                this["DefaultMoney"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("این یک یادداشت تست است!")]
        public string Note {
            get {
                return ((string)(this["Note"]));
            }
            set {
                this["Note"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public decimal Timer {
            get {
                return ((decimal)(this["Timer"]));
            }
            set {
                this["Timer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal WarningTimer {
            get {
                return ((decimal)(this["WarningTimer"]));
            }
            set {
                this["WarningTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("تایمر استراحت چشم")]
        public string Title {
            get {
                return ((string)(this["Title"]));
            }
            set {
                this["Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Arash\\source\\repos")]
        public string QuickAccessAddress1 {
            get {
                return ((string)(this["QuickAccessAddress1"]));
            }
            set {
                this["QuickAccessAddress1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Programming\\Supporting")]
        public string QuickAccessAddress2 {
            get {
                return ((string)(this["QuickAccessAddress2"]));
            }
            set {
                this["QuickAccessAddress2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Programming\\Supporting\\برنامه هفتگی.pdf")]
        public string QuickAccessAddress3 {
            get {
                return ((string)(this["QuickAccessAddress3"]));
            }
            set {
                this["QuickAccessAddress3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\University\\ترم سوم")]
        public string QuickAccessAddress4 {
            get {
                return ((string)(this["QuickAccessAddress4"]));
            }
            set {
                this["QuickAccessAddress4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Programming\\Education\\Coding\\Atria\\ASP.NET")]
        public string QuickAccessAddress5 {
            get {
                return ((string)(this["QuickAccessAddress5"]));
            }
            set {
                this["QuickAccessAddress5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Film\\سریال ایرانی")]
        public string QuickAccessAddress6 {
            get {
                return ((string)(this["QuickAccessAddress6"]));
            }
            set {
                this["QuickAccessAddress6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Film\\Vikings")]
        public string QuickAccessAddress7 {
            get {
                return ((string)(this["QuickAccessAddress7"]));
            }
            set {
                this["QuickAccessAddress7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("پروژه های ویژوال استودیو")]
        public string QuickAccessName1 {
            get {
                return ((string)(this["QuickAccessName1"]));
            }
            set {
                this["QuickAccessName1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("پشتیبانی")]
        public string QuickAccessName2 {
            get {
                return ((string)(this["QuickAccessName2"]));
            }
            set {
                this["QuickAccessName2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("برنامه هفتگی")]
        public string QuickAccessName3 {
            get {
                return ((string)(this["QuickAccessName3"]));
            }
            set {
                this["QuickAccessName3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("دانشگاه")]
        public string QuickAccessName4 {
            get {
                return ((string)(this["QuickAccessName4"]));
            }
            set {
                this["QuickAccessName4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("دوره آتریا")]
        public string QuickAccessName5 {
            get {
                return ((string)(this["QuickAccessName5"]));
            }
            set {
                this["QuickAccessName5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("فیلم و سریال ایرانی")]
        public string QuickAccessName6 {
            get {
                return ((string)(this["QuickAccessName6"]));
            }
            set {
                this["QuickAccessName6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("سریال وایکینگز")]
        public string QuickAccessName7 {
            get {
                return ((string)(this["QuickAccessName7"]));
            }
            set {
                this["QuickAccessName7"] = value;
            }
        }
    }
}
